version: '3.4'

services:
  graficas.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32780:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro